create table CROP
(
    CROP_SHORT_NAME VARCHAR2(32),
    CROP_NAME       VARCHAR2(128),
    ADDRESS         VARCHAR2(256),
    CONTACT_PERSON  VARCHAR2(16),
    CONTACT_WAY     VARCHAR2(16),
    TOKEN_URL       VARCHAR2(256),
    TOKEN_SECRET    VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP,
    CREATE_TIME     TIMESTAMP
)