create table SUB_ACCOUNT
(
    ACCO_D VARCHAR2(32),
    ACCO_NO VARCHAR2(32),
    ACCO_NAME         VARCHAR2(256),
    SUB_ACCO_ID VARCHAR2(32),
    UPDATE_TIME     TIMESTAMP,
    CREATE_TIME     TIMESTAMP
)